# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        types: [python]
      - id: end-of-file-fixer
        types: [python]
      - id: trailing-whitespace
        types: [yaml]
      - id: end-of-file-fixer
        types: [yaml]
      - id: check-yaml
      - id: check-ast
      - id: debug-statements
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        args: [--ignore-missing-imports, --disallow-untyped-defs, --disallow-incomplete-defs, --no-implicit-optional]
        exclude: ^test/
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.8.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==20.8b1]
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.8.3"
    hooks:
      - id: flake8
        args: [--max-line-length=120, --doctests]
        exclude: ^test/
  - repo: local
    hooks:
      - id: export-conda-environment
        name: export-conda-environment
        entry: pre-commit-scripts/export_conda_env.sh
        language: script
      - id: build-docs
        name: build-docs
        entry: pre-commit-scripts/build_docs.sh
        language: script
